version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /build/container
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /development/app
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /development/app
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /python/aibrix/aibrix/gpu_optimizer/optimizer/solver/melange
    schedule:
      interval: daily
